// app/components/contact/contact.component.ts
import { Component } from '@angular/core';
import { socialLinks } from '../../../constants';

@Component({
  selector: 'app-contact',
  templateUrl: './contact.component.html'
})
export class ContactComponent {
  socialLinks = socialLinks;
}

<section id="contact" class="py-20 bg-[#191923]">
  <div class="container mx-auto px-6 text-center">
    <h2 class="text-4xl font-bold mb-4 text-white">Get In <span class="text-[#F75023]">Touch</span></h2>
    <p class="text-lg text-gray-400 max-w-2xl mx-auto mb-8">
      I'm currently open to new opportunities and collaborations. Feel free to reach out if you have a project in mind or just want to connect!
    </p>
    <a href="mailto:meet.mori@example.com" class="inline-block bg-[#F75023] text-white font-bold py-3 px-8 rounded-md hover:bg-opacity-80 transition-all duration-300 text-lg mb-12">
      Say Hello
    </a>
    <div class="flex justify-center space-x-6">
        <a *ngFor="let link of socialLinks" [href]="link.url" target="_blank" rel="noopener noreferrer" class="text-gray-400 hover:text-[#F75023] transition-colors duration-300">
           <i class="{{link.icon}} text-4xl"></i>
       </a>
    </div>
  </div>
</section>

// components/Contact.tsx
import React from 'react';
import { socialLinks } from '../constants';

const Contact: React.FC = () => {
  return (
    <section id="contact" className="py-20 bg-[#191923]">
      <div className="container mx-auto px-6 text-center">
        <h2 className="text-4xl font-bold mb-4 text-white">Get In <span className="text-[#F75023]">Touch</span></h2>
        <p className="text-lg text-gray-400 max-w-2xl mx-auto mb-8">
          I'm currently open to new opportunities and collaborations. Feel free to reach out if you have a project in mind or just want to connect!
        </p>
        <a href="mailto:meet.mori@example.com" className="inline-block bg-[#F75023] text-white font-bold py-3 px-8 rounded-md hover:bg-opacity-80 transition-all duration-300 text-lg mb-12">
          Say Hello
        </a>
        <div className="flex justify-center space-x-6">
            {socialLinks.map(link => (
                 <a key={link.name} href={link.url} target="_blank" rel="noopener noreferrer" className="text-gray-400 hover:text-[#F75023] transition-colors duration-300">
                    <i className={`${link.icon} text-4xl`}></i>
                </a>
            ))}
        </div>
      </div>
    </section>
  );
};

export default Contact;
